#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

capistrano_deploy - Plugin to Capistrano deploy count.

=head1 AUTHOR

Contributed by Takeshi Yako
https://github.com/takeshiyako2

=head1 LICENSE

MIT

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi
if [ "$1" = "config" ]; then

        echo 'graph_title Capistrano deploy'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel count in days'
        echo 'graph_category system'
        echo 'capistrano_deploy.label count'
        echo 'capistrano_deploy.draw AREA'
        exit 0
fi

REVISIONS_LOG=${log}
TODAY=`date '+%Y%m%d'`
COUNT=`grep "$TODAY" $REVISIONS_LOG | wc -l`
printf "count.value $COUNT\n"
